spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/bank_management
    username: root
    password: saurav 
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
